#!/usr/bin/env python3
"""AI Dev Team — platform installer & verifier.

Usage:
    python install.py --platform claude-code      # register MCP + rules file
    python install.py --hooks-only                # install post-commit hook only
    python install.py --verify                    # health check (Integration.md Part 4)
    python install.py --init                      # create .ai-devteam/ + .env skeleton

Default platform is `claude-code` if `--platform` is omitted.
"""
from __future__ import annotations

import argparse
import http.client
import json
import logging
import os
import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path

# Allow `python install.py` from repo root without installing the package.
REPO_ROOT = Path(__file__).resolve().parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from plugin.config import settings  # noqa: E402
from plugin.integrations import GENERATORS, list_platforms, run_install  # noqa: E402
from plugin.paths import ai_devteam_dir, config_file, ensure_dirs, project_root  # noqa: E402
from plugin.triggers.git_hook import install_hook as install_post_commit_hook  # noqa: E402

logger = logging.getLogger("install")


# ---------- tiny print helpers --------------------------------------------------

TICK = "✓"
CROSS = "✗"
WARN = "!"


def _green(s: str) -> str:
    return f"\033[32m{s}\033[0m"


def _red(s: str) -> str:
    return f"\033[31m{s}\033[0m"


def _yellow(s: str) -> str:
    return f"\033[33m{s}\033[0m"


def _safe_print(s: str) -> None:
    """Print a unicode-safe line on Windows (cp1252) consoles."""
    try:
        print(s)
    except UnicodeEncodeError:
        # Replace non-encodable chars with ASCII equivalents.
        enc = sys.stdout.encoding or "utf-8"
        print(s.encode(enc, errors="replace").decode(enc, errors="replace"))


def _check(name: str, ok: bool, detail: str = "", *, warn: bool = False) -> bool:
    """Print one check line. Returns ok."""
    if ok:
        marker = _green(TICK)
        msg = _green(f"{name:<24} set" if warn is False else f"{name:<24} {detail}")
        _safe_print(f"  {marker} {msg}")
    elif warn:
        marker = _yellow(WARN)
        msg = _yellow(f"{name:<24} {detail or 'not set (optional)'}")
        _safe_print(f"  {marker} {msg}")
    else:
        marker = _red(CROSS)
        msg = _red(f"{name:<24} {detail or 'failed'}")
        _safe_print(f"  {marker} {msg}")
    return ok


# ---------- --init --------------------------------------------------------------

DEFAULT_CONFIG_TOML = """# AI Dev Team — per-project config
# Generated by `python install.py --init`. Edit freely.

[models]
planning = "{planning}"
code     = "{code}"
review   = "{review}"
docs     = "{docs}"

[memory]
ltm = "auto"   # "auto" = use Qdrant if reachable, else skip
"""


def cmd_init(args: argparse.Namespace) -> int:
    """Create `.ai-devteam/` tree, write `config.toml`, copy `.env.example` → `.env`."""
    dirs = ensure_dirs()
    print(_green(f"Created .ai-devteam/ subdirs: {', '.join(p.name for p in dirs.values())}"))

    cfg = config_file()
    if not cfg.exists():
        cfg.write_text(
            DEFAULT_CONFIG_TOML.format(
                planning=settings.PLANNING_MODEL,
                code=settings.CODE_MODEL,
                review=settings.REVIEW_MODEL,
                docs=settings.DOCS_MODEL,
            ),
            encoding="utf-8",
        )
        print(_green(f"Wrote {cfg.relative_to(project_root())}"))
    else:
        print(_yellow(f"Skipped (already present): {cfg.relative_to(project_root())}"))

    env_example = REPO_ROOT / ".env.example"
    env_file = project_root() / ".env"
    if env_example.exists() and not env_file.exists():
        shutil.copy(env_example, env_file)
        print(_green(f"Copied .env.example -> {env_file.relative_to(project_root())}"))
    elif env_file.exists():
        print(_yellow(f"Skipped (already present): .env"))
    else:
        print(_yellow("No .env.example found at repo root — please create .env manually."))

    return 0


# ---------- --hooks-only --------------------------------------------------------

def cmd_hooks(args: argparse.Namespace) -> int:
    """Install the post-commit git hook only."""
    hook_path = install_post_commit_hook()
    if hook_path:
        print(_green(f"Installed post-commit hook: {hook_path}"))
        return 0
    print(_yellow("Not inside a git repo — hook not installed. Run `git init` first."))
    return 0


# ---------- --platform ----------------------------------------------------------

def cmd_platform(args: argparse.Namespace) -> int:
    """Run a platform generator."""
    platform = args.platform or "claude-code"
    if platform not in GENERATORS:
        print(_red(f"Unknown platform '{platform}'. Available: {', '.join(list_platforms())}"))
        return 2

    server_command = _default_server_command()
    result = run_install(platform, project_root(), server_command)

    for path_str in result.get("written", []):
        rel = Path(path_str)
        try:
            rel = rel.relative_to(project_root())
        except ValueError:
            pass
        print(_green(f"  {TICK} wrote {rel}"))
    print(_green(result.get("message", "Done.")))

    # Always install the post-commit hook alongside platform setup so /docs works.
    hook_path = install_post_commit_hook()
    if hook_path:
        print(_green(f"  {TICK} installed post-commit hook at {hook_path}"))
    else:
        print(_yellow(f"  {WARN} git repo not initialised — run `git init` to enable the hook"))

    # Verify after install unless suppressed.
    if not args.no_verify:
        print()
        print(_green("Running --verify ..."))
        return cmd_verify(args)
    return 0


def _default_server_command() -> list[str]:
    """The argv the platform will spawn to start the MCP server."""
    return [sys.executable, "-m", "plugin.server"]


# ---------- --verify ------------------------------------------------------------

def cmd_verify(args: argparse.Namespace) -> int:
    """Health check — Integration.md Part 4."""
    print(_green("AI Dev Team — install verification"))
    print()

    failures = 0

    # Required env.
    if not _check("GROQ_API_KEY", bool(settings.GROQ_API_KEY), "not set"):
        failures += 1

    # Optional envs (warnings, not failures).
    for name, label in [
        ("LANGCHAIN_API_KEY", "LANGCHAIN_API_KEY"),
        ("TAVILY_API_KEY", "TAVILY_API_KEY"),
        ("EXA_API_KEY", "EXA_API_KEY"),
        ("FIRECRAWL_API_KEY", "FIRECRAWL_API_KEY"),
        ("GITHUB_TOKEN", "GITHUB_TOKEN"),
        ("QDRANT_API_KEY", "QDRANT_API_KEY"),
    ]:
        val = getattr(settings, name, "")
        _check(label, bool(val), warn=True)

    # Qdrant reachability.
    qdrant_ok = _check_qdrant_reachable(settings.QDRANT_URL)
    if not qdrant_ok:
        # Qdrant is optional (graceful degradation) — surface but don't fail.
        _check("Qdrant", False, f"unreachable at {settings.QDRANT_URL}", warn=True)

    # MCP server boot.
    if not _check_mcp_server_boot():
        failures += 1

    # Platform rules file (claude-code by default).
    platform = args.platform or "claude-code"
    rules_path = _rules_file_for_platform(platform, project_root())
    if rules_path and rules_path.exists():
        _check(f"Platform ({platform})", True, f"{rules_path.name} present")
    else:
        if rules_path is None:
            _check(f"Platform ({platform})", True, "no rules file required", warn=True)
        else:
            _check(f"Platform ({platform})", False, f"{rules_path.name} missing")
            failures += 1

    # Git hook.
    hook_path = project_root() / ".git" / "hooks" / "post-commit"
    if hook_path.exists():
        _check("Git hooks", True, "post-commit installed")
    else:
        _check("Git hooks", False, "post-commit missing")
        failures += 1

    print()
    if failures == 0:
        print(_green("All required checks passed."))
        return 0
    print(_red(f"{failures} required check(s) failed."))
    return 1


def _check_qdrant_reachable(url: str, timeout: float = 2.0) -> bool:
    """Cheap HTTP probe — `GET /` on Qdrant. Returns True if 200/4xx."""
    try:
        if url.startswith("https://"):
            host_port = url[len("https://"):].split("/", 1)[0]
            conn = http.client.HTTPSConnection(host_port, timeout=timeout)
        else:
            host_port = url[len("http://"):].split("/", 1)[0]
            conn = http.client.HTTPConnection(host_port, timeout=timeout)
        conn.request("GET", "/")
        resp = conn.getresponse()
        _ = resp.read()
        conn.close()
        # Qdrant returns 200 on root.
        return 200 <= resp.status < 500
    except Exception as e:
        logger.debug("Qdrant unreachable: %s", e)
        return False


def _check_mcp_server_boot(timeout: float = 5.0) -> bool:
    """Spawn the MCP server in stdio mode for a short period and check it doesn't crash on startup."""
    try:
        proc = subprocess.Popen(
            [sys.executable, "-m", "plugin.server", "--transport", "stdio"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            cwd=str(REPO_ROOT),
        )
        # The server blocks on stdio — give it a moment to crash if misconfigured.
        time.sleep(2.0)
        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=2)
            except subprocess.TimeoutExpired:
                proc.kill()
            return True
        # Exited early — surface stderr for debugging.
        _, err = proc.communicate(timeout=1)
        msg = err.decode("utf-8", errors="replace").strip().splitlines()[-1] if err else "exit"
        _check("MCP server", False, f"crashed on startup: {msg}")
        return False
    except Exception as e:
        _check("MCP server", False, f"could not launch: {e}")
        return False


def _rules_file_for_platform(platform: str, root: Path) -> Path | None:
    if platform == "claude-code":
        return root / "CLAUDE.md"
    if platform == "cline":
        return root / ".clinerules"
    if platform == "roocode":
        return root / ".roorules"
    # OpenCode / Codex: no rules file.
    return None


# ---------- main ----------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="AI Dev Team — install / verify the plugin for your coding platform.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--platform",
        choices=list_platforms(),
        help="Target coding platform (default: claude-code).",
    )
    p.add_argument(
        "--hooks-only",
        action="store_true",
        help="Install only the post-commit git hook.",
    )
    p.add_argument(
        "--init",
        action="store_true",
        help="Create .ai-devteam/ + config.toml + .env (run once per project).",
    )
    p.add_argument(
        "--verify",
        action="store_true",
        help="Run health checks (env, Qdrant, MCP server, platform file, hook).",
    )
    p.add_argument(
        "--no-verify",
        action="store_true",
        help="Skip the --verify step after --platform.",
    )
    return p


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.WARNING, format="%(message)s")
    parser = build_parser()
    args = parser.parse_args(argv)

    # Reconfigure stdout to UTF-8 so the ✓ / ✗ marks render on Windows cp1252.
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

    # Allow colour to be disabled (CI / piped output).
    if not sys.stdout.isatty():
        global _green, _red, _yellow
        _green = _red = _yellow = lambda s: s  # noqa: E731

    if args.verify:
        return cmd_verify(args)
    if args.init:
        return cmd_init(args)
    if args.hooks_only:
        return cmd_hooks(args)
    if args.platform or True:  # default action when nothing else matches
        return cmd_platform(args)


if __name__ == "__main__":
    sys.exit(main())
