import os
import tempfile
import subprocess
from typing import Optional
from app.config import settings
import logging

logger = logging.getLogger(__name__)


def _run_git(args: list[str], cwd: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git"] + args,
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=60
    )


def _github_api(endpoint: str, data: dict, method: str = "POST") -> dict:
    """Call GitHub REST API using curl (no extra dependencies)."""
    import json
    token = settings.GITHUB_TOKEN
    owner = settings.GITHUB_USERNAME
    url = f"https://api.github.com/{endpoint}"

    payload = json.dumps(data)

    result = subprocess.run(
        [
            "curl", "-s", "-X", method, url,
            "-H", f"Authorization: token {token}",
            "-H", "Accept: application/vnd.github+json",
            "-H", "Content-Type: application/json",
            "-d", payload
        ],
        capture_output=True,
        text=True,
        timeout=30
    )

    if result.returncode != 0:
        raise RuntimeError(f"GitHub API call failed: {result.stderr}")

    return json.loads(result.stdout)


def github_commit_and_pr(
    files: dict[str, str],
    project_name: str,
    repo_name: Optional[str] = None
) -> str:
    """Write files to a local repo, commit, push, and create a PR. Returns PR URL."""
    if not settings.GITHUB_TOKEN or not settings.GITHUB_USERNAME:
        raise RuntimeError("GITHUB_TOKEN and GITHUB_USERNAME must be set")

    repo_name = repo_name or project_name.lower().replace(" ", "-")

    with tempfile.TemporaryDirectory() as tmp:
        logger.info(f"Initializing git repo for {project_name}")

        _run_git(["init"], cwd=tmp)
        _run_git(["checkout", "-b", f"feature/{repo_name}"], cwd=tmp)

        for rel_path, content in files.items():
            full = os.path.join(tmp, rel_path)
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w", encoding="utf-8") as f:
                f.write(content)

        _run_git(["add", "-A"], cwd=tmp)
        _run_git(["commit", "-m", f"feat: AI-generated {project_name}"], cwd=tmp)

        _run_git(["remote", "add", "origin", f"https://{settings.GITHUB_TOKEN}@github.com/{settings.GITHUB_USERNAME}/{repo_name}.git"], cwd=tmp)

        push_result = _run_git(["push", "-u", "origin", f"feature/{repo_name}", "--force"], cwd=tmp)
        if push_result.returncode != 0:
            logger.warning(f"Push failed (repo may not exist): {push_result.stderr.strip()}")

        try:
            _github_api(
                f"repos/{settings.GITHUB_USERNAME}/{repo_name}/pulls",
                {"title": f"feat: AI-generated {project_name}", "body": "Auto-generated by AI Dev Team", "head": f"feature/{repo_name}", "base": "main"}
            )
            pr_url = f"https://github.com/{settings.GITHUB_USERNAME}/{repo_name}/pulls"
        except Exception as e:
            logger.warning(f"PR creation failed: {e}")
            pr_url = f"https://github.com/{settings.GITHUB_USERNAME}/{repo_name}"

        return pr_url
